---
title: 'Task 04: Quiz'
author: "Mark Blackmore"
date: "October 30, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

For each of the sentence fragments below use your natural language processing algorithm to predict the next word in the sentence.

Q1. The guy in front of me just bought a pound of bacon, a bouquet, and a case of  

  * cheese
  * pretzels
  * beer
  * soda  

Q2. You're the reason why I smile everyday. Can you follow me please? It would mean the 

  * universe
  * most
  * world
  * best

Q3. Hey sunshine, can you follow me and make me the  

  * happiest
  * bluest
  * saddest
  * smelliest

Q4. Very early observations on the Bills game: Offense still struggling but the  

  * referees
  * players
  * crowd
  * defense

Q5. Go on a romantic date at the  

  * mall
  * movies
  * beach
  * grocery

Q6. Well I'm pretty sure my granny has some old bagpipes in her garage I'll dust them off and be on my  

  * horse
  * phone
  * way
  * motorcycle

Q7. Ohhhhh #PointBreak is on tomorrow. Love that film and haven't seen it in quite some

  * time
  * thing
  * weeks
  * years

Q8. After the ice bucket challenge Louis will push his long wet hair out of his eyes with his little

  * toes
  * ears
  * eyes
  * fingers

Q9. Be grateful for the good times and keep the faith during the

  * hard
  * bad
  * sad
  * worse

Q10. If this isn't the cutest thing you've ever seen, then you must be

  * insane
  * asleep
  * callous
  * insensitive
