---
title: "Task 05: Quiz"
author: "Mark Blackmore"
date: "November 8, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1. 
For each of the sentence fragments below use your natural language processing algorithm to predict the next word in the sentence.

When you breathe, I want to be the air for you. I'll be there for you, I'd live and I'd

sleep

give

die

eat
1
point
2. 
Guy at my table's wife got up to go to the bathroom and I asked about dessert and he started telling me about his

horticultural

marital

spiritual

financial
1
point
3. 
I'd give anything to see arctic monkeys this

weekend

decade

month

morning
1
point
4. 
Talking to your mom has the same effect as a hug and helps reduce your

sleepiness

happiness

hunger

stress
1
point
5. 
When you were in Holland you were like 1 inch away from me but you hadn't time to take a

walk

minute

look

picture
1
point
6. 
I'd just like all of these questions answered, a presentation of evidence, and a jury to settle the

account

case

matter

incident
1
point
7. 
I can't deal with unsymetrical things. I can't even hold an uneven number of bags of groceries in each

hand

finger

toe

arm
1
point
8. 
Every inch of you is perfect from the bottom to the

top

middle

center

side
1
point
9. 
I'm thankful my childhood was filled with imagination and bruises from playing

weekly

inside

outside

daily
1
point
10. 
I like how the same people are in almost all of Adam Sandler's

movies

stories

pictures

novels